# Generated by Django 5.2.1 on 2025-06-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_speechcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechcard',
            name='created_at',
        ),
    ]
