# Generated by Django 5.2.1 on 2025-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='three_things_i_love',
            field=models.CharField(default='Books, Coffee, Rainy Days', max_length=255),
        ),
    ]
