# Generated by Django 5.2.1 on 2025-05-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_three_things_i_love'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='three_things_i_love',
        ),
    ]
