# Generated by Django 5.2.1 on 2025-06-01 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_speechcard_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechcard',
            name='image',
            field=models.ImageField(upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='speechcard',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='speechcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
