# Generated by Django 5.2.1 on 2025-06-03 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_speechcard_image_alter_speechcard_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speechcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='speechcard',
            name='image',
            field=models.ImageField(upload_to='card_images/'),
        ),
        migrations.AlterField(
            model_name='speechcard',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='speechcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
